name: lib_llama_cpp_example
description: Example app for the lib_llama_cpp Flutter plugin.
publish_to: none
version: 0.7.3+1

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  lib_llama_cpp:
    path: ../packages/lib_llama_cpp
  lib_llama_cpp_ffi:
    path: ../packages/lib_llama_cpp_ffi
  lib_llama_cpp_platform_interface:
    path: ../packages/lib_llama_cpp_platform_interface

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/e2e/
