name: lib_llama_cpp_platform_interface
description: Platform interface for the lib_llama_cpp federated Flutter FFI plugin.
version: 0.5.4
repository: https://github.com/gsmlg-app/lib_llama_cpp

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
